### ISSUE TITLE
record._internalModel.flushChangedAttributes is not a function

### ISSUE THREAD

**Issue by GCorbel** [laborvoices/ember-data-save-relationships#10]
I'm working on a app built with Ember 3.5 and, when I save a new record, I have the error "record._internalModel.flushChangedAttributes is not a function". I suppose this is an old function and it had been removed but I didn't found it, even in old versions of ember.

By the way, is there a plan to support Ember 3 officially?

**Comment by GCorbel** [comment]
I override the method and removed the line in error. It seems to works. `record.changedAttributes()` give and empty array in the end.
