### PR TITLE
Remove old flushChangedAttributes()

### LINKED ISSUE #10: record._internalModel.flushChangedAttributes is not a function
I'm working on a app built with Ember 3.5 and, when I save a new record, I have the error "record._internalModel.flushChangedAttributes is not a function". I suppose this is an old function and it had been removed but I didn't found it, even in old versions of ember.

By the way, is there a plan to support Ember 3 officially?

### PR DESCRIPTION
**Pull request by mhluska**
Fixes https://github.com/laborvoices/ember-data-save-relationships/issues/10

### CODE REVIEW

**Comment by MatthewSBarnes** [comment]
@psteininger Nudge.

**Comment by Gamma169** [comment]
@psteininger Nudge again.

**Comment by psteininger** [comment]
I am so sorry I missed this @mhluska @matthewsbarnes @gamma169. I think the notifications went to my former work email or got buried in the "forums" tabs.
